// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/application/bot/handler (interfaces: TelegramBotHandler)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pkg "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain/pkg"
)

// MockTelegramBotHandler is a mock of TelegramBotHandler interface.
type MockTelegramBotHandler struct {
	ctrl     *gomock.Controller
	recorder *MockTelegramBotHandlerMockRecorder
}

// MockTelegramBotHandlerMockRecorder is the mock recorder for MockTelegramBotHandler.
type MockTelegramBotHandlerMockRecorder struct {
	mock *MockTelegramBotHandler
}

// NewMockTelegramBotHandler creates a new mock instance.
func NewMockTelegramBotHandler(ctrl *gomock.Controller) *MockTelegramBotHandler {
	mock := &MockTelegramBotHandler{ctrl: ctrl}
	mock.recorder = &MockTelegramBotHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelegramBotHandler) EXPECT() *MockTelegramBotHandlerMockRecorder {
	return m.recorder
}

// HandleLinkUpdate mocks base method.
func (m *MockTelegramBotHandler) HandleLinkUpdate(arg0 pkg.LinkUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleLinkUpdate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleLinkUpdate indicates an expected call of HandleLinkUpdate.
func (mr *MockTelegramBotHandlerMockRecorder) HandleLinkUpdate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLinkUpdate", reflect.TypeOf((*MockTelegramBotHandler)(nil).HandleLinkUpdate), arg0)
}
