// Code generated by MockGen. DO NOT EDIT.
// Source: server.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	shared "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain/shared"
)

// MockScrapperHandler is a mock of ScrapperHandler interface.
type MockScrapperHandler struct {
	ctrl     *gomock.Controller
	recorder *MockScrapperHandlerMockRecorder
}

// MockScrapperHandlerMockRecorder is the mock recorder for MockScrapperHandler.
type MockScrapperHandlerMockRecorder struct {
	mock *MockScrapperHandler
}

// NewMockScrapperHandler creates a new mock instance.
func NewMockScrapperHandler(ctrl *gomock.Controller) *MockScrapperHandler {
	mock := &MockScrapperHandler{ctrl: ctrl}
	mock.recorder = &MockScrapperHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScrapperHandler) EXPECT() *MockScrapperHandlerMockRecorder {
	return m.recorder
}

// AddChatId mocks base method.
func (m *MockScrapperHandler) AddChatId(chatId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChatId", chatId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChatId indicates an expected call of AddChatId.
func (mr *MockScrapperHandlerMockRecorder) AddChatId(chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChatId", reflect.TypeOf((*MockScrapperHandler)(nil).AddChatId), chatId)
}

// AddLink mocks base method.
func (m *MockScrapperHandler) AddLink(chatId int64, linkRequest shared.AddLinkRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", chatId, linkRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLink indicates an expected call of AddLink.
func (mr *MockScrapperHandlerMockRecorder) AddLink(chatId, linkRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockScrapperHandler)(nil).AddLink), chatId, linkRequest)
}

// DeleteChat mocks base method.
func (m *MockScrapperHandler) DeleteChat(chatId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", chatId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockScrapperHandlerMockRecorder) DeleteChat(chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockScrapperHandler)(nil).DeleteChat), chatId)
}

// DeleteLink mocks base method.
func (m *MockScrapperHandler) DeleteLink(chatId int64, link string) (shared.LinkInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", chatId, link)
	ret0, _ := ret[0].(shared.LinkInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockScrapperHandlerMockRecorder) DeleteLink(chatId, link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockScrapperHandler)(nil).DeleteLink), chatId, link)
}

// GetLinks mocks base method.
func (m *MockScrapperHandler) GetLinks(chatId int64) ([]shared.LinkInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinks", chatId)
	ret0, _ := ret[0].([]shared.LinkInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinks indicates an expected call of GetLinks.
func (mr *MockScrapperHandlerMockRecorder) GetLinks(chatId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinks", reflect.TypeOf((*MockScrapperHandler)(nil).GetLinks), chatId)
}
