// Code generated by MockGen. DO NOT EDIT.
// Source: links_handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	shared "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain/pkg"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddChat mocks base method.
func (m *MockRepository) AddChat(chatID int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddChat", chatID)
}

// AddChat indicates an expected call of AddChat.
func (mr *MockRepositoryMockRecorder) AddChat(chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChat", reflect.TypeOf((*MockRepository)(nil).AddChat), chatID)
}

// AddLink mocks base method.
func (m *MockRepository) AddLink(chatID int64, link shared.LinkInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddLink", chatID, link)
}

// AddLink indicates an expected call of AddLink.
func (mr *MockRepositoryMockRecorder) AddLink(chatID, link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockRepository)(nil).AddLink), chatID, link)
}

// ChatExists mocks base method.
func (m *MockRepository) ChatExists(chatID int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatExists", chatID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ChatExists indicates an expected call of ChatExists.
func (mr *MockRepositoryMockRecorder) ChatExists(chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatExists", reflect.TypeOf((*MockRepository)(nil).ChatExists), chatID)
}

// DeleteChat mocks base method.
func (m *MockRepository) DeleteChat(chatID int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteChat", chatID)
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockRepositoryMockRecorder) DeleteChat(chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockRepository)(nil).DeleteChat), chatID)
}

// DeleteLink mocks base method.
func (m *MockRepository) DeleteLink(chatID int64, link string) (shared.LinkInfo, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", chatID, link)
	ret0, _ := ret[0].(shared.LinkInfo)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockRepositoryMockRecorder) DeleteLink(chatID, link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockRepository)(nil).DeleteLink), chatID, link)
}

// GetAllLinks mocks base method.
func (m *MockRepository) GetAllLinks() []shared.LinkInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLinks")
	ret0, _ := ret[0].([]shared.LinkInfo)
	return ret0
}

// GetAllLinks indicates an expected call of GetAllLinks.
func (mr *MockRepositoryMockRecorder) GetAllLinks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLinks", reflect.TypeOf((*MockRepository)(nil).GetAllLinks))
}

// GetChatIDsByLink mocks base method.
func (m *MockRepository) GetChatIDsByLink(link string) []int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatIDsByLink", link)
	ret0, _ := ret[0].([]int64)
	return ret0
}

// GetChatIDsByLink indicates an expected call of GetChatIDsByLink.
func (mr *MockRepositoryMockRecorder) GetChatIDsByLink(link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatIDsByLink", reflect.TypeOf((*MockRepository)(nil).GetChatIDsByLink), link)
}

// GetLinks mocks base method.
func (m *MockRepository) GetLinks(chatID int64) []shared.LinkInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinks", chatID)
	ret0, _ := ret[0].([]shared.LinkInfo)
	return ret0
}

// GetLinks indicates an expected call of GetLinks.
func (mr *MockRepositoryMockRecorder) GetLinks(chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinks", reflect.TypeOf((*MockRepository)(nil).GetLinks), chatID)
}

// UpdateLinksTime mocks base method.
func (m *MockRepository) UpdateLinksTime(newTime time.Time, linkToUpdate shared.LinkInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateLinksTime", newTime, linkToUpdate)
}

// UpdateLinksTime indicates an expected call of UpdateLinksTime.
func (mr *MockRepositoryMockRecorder) UpdateLinksTime(newTime, linkToUpdate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLinksTime", reflect.TypeOf((*MockRepository)(nil).UpdateLinksTime), newTime, linkToUpdate)
}
