// Code generated by MockGen. DO NOT EDIT.
// Source: links_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	pkg "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain/pkg"
)

// MockLinkRepository is a mock of LinkRepository interface.
type MockLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRepositoryMockRecorder
}

// MockLinkRepositoryMockRecorder is the mock recorder for MockLinkRepository.
type MockLinkRepositoryMockRecorder struct {
	mock *MockLinkRepository
}

// NewMockLinkRepository creates a new mock instance.
func NewMockLinkRepository(ctrl *gomock.Controller) *MockLinkRepository {
	mock := &MockLinkRepository{ctrl: ctrl}
	mock.recorder = &MockLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRepository) EXPECT() *MockLinkRepositoryMockRecorder {
	return m.recorder
}

// AddLink mocks base method.
func (m *MockLinkRepository) AddLink(ctx context.Context, chatID int64, link pkg.LinkInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", ctx, chatID, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLink indicates an expected call of AddLink.
func (mr *MockLinkRepositoryMockRecorder) AddLink(ctx, chatID, link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockLinkRepository)(nil).AddLink), ctx, chatID, link)
}

// DeleteLink mocks base method.
func (m *MockLinkRepository) DeleteLink(ctx context.Context, chatID int64, url string) (pkg.LinkInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", ctx, chatID, url)
	ret0, _ := ret[0].(pkg.LinkInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockLinkRepositoryMockRecorder) DeleteLink(ctx, chatID, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockLinkRepository)(nil).DeleteLink), ctx, chatID, url)
}

// GetAllLinks mocks base method.
func (m *MockLinkRepository) GetAllLinks(ctx context.Context, limit, offset int) ([]pkg.LinkInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLinks", ctx, limit, offset)
	ret0, _ := ret[0].([]pkg.LinkInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLinks indicates an expected call of GetAllLinks.
func (mr *MockLinkRepositoryMockRecorder) GetAllLinks(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLinks", reflect.TypeOf((*MockLinkRepository)(nil).GetAllLinks), ctx, limit, offset)
}

// GetChatIDsByLink mocks base method.
func (m *MockLinkRepository) GetChatIDsByLink(ctx context.Context, link string) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatIDsByLink", ctx, link)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatIDsByLink indicates an expected call of GetChatIDsByLink.
func (mr *MockLinkRepositoryMockRecorder) GetChatIDsByLink(ctx, link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatIDsByLink", reflect.TypeOf((*MockLinkRepository)(nil).GetChatIDsByLink), ctx, link)
}

// GetUserLinks mocks base method.
func (m *MockLinkRepository) GetUserLinks(ctx context.Context, chatID int64) ([]pkg.LinkInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserLinks", ctx, chatID)
	ret0, _ := ret[0].([]pkg.LinkInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserLinks indicates an expected call of GetUserLinks.
func (mr *MockLinkRepositoryMockRecorder) GetUserLinks(ctx, chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserLinks", reflect.TypeOf((*MockLinkRepository)(nil).GetUserLinks), ctx, chatID)
}

// LinkExists mocks base method.
func (m *MockLinkRepository) LinkExists(ctx context.Context, url string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkExists", ctx, url)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkExists indicates an expected call of LinkExists.
func (mr *MockLinkRepositoryMockRecorder) LinkExists(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkExists", reflect.TypeOf((*MockLinkRepository)(nil).LinkExists), ctx, url)
}

// UpdateLinksTime mocks base method.
func (m *MockLinkRepository) UpdateLinksTime(ctx context.Context, newTime time.Time, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLinksTime", ctx, newTime, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLinksTime indicates an expected call of UpdateLinksTime.
func (mr *MockLinkRepositoryMockRecorder) UpdateLinksTime(ctx, newTime, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLinksTime", reflect.TypeOf((*MockLinkRepository)(nil).UpdateLinksTime), ctx, newTime, url)
}

// MockChatRepository is a mock of ChatRepository interface.
type MockChatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChatRepositoryMockRecorder
}

// MockChatRepositoryMockRecorder is the mock recorder for MockChatRepository.
type MockChatRepositoryMockRecorder struct {
	mock *MockChatRepository
}

// NewMockChatRepository creates a new mock instance.
func NewMockChatRepository(ctrl *gomock.Controller) *MockChatRepository {
	mock := &MockChatRepository{ctrl: ctrl}
	mock.recorder = &MockChatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatRepository) EXPECT() *MockChatRepositoryMockRecorder {
	return m.recorder
}

// AddChat mocks base method.
func (m *MockChatRepository) AddChat(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChat", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChat indicates an expected call of AddChat.
func (mr *MockChatRepositoryMockRecorder) AddChat(ctx, chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChat", reflect.TypeOf((*MockChatRepository)(nil).AddChat), ctx, chatID)
}

// ChatExists mocks base method.
func (m *MockChatRepository) ChatExists(ctx context.Context, chatID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatExists", ctx, chatID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatExists indicates an expected call of ChatExists.
func (mr *MockChatRepositoryMockRecorder) ChatExists(ctx, chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatExists", reflect.TypeOf((*MockChatRepository)(nil).ChatExists), ctx, chatID)
}

// DeleteChat mocks base method.
func (m *MockChatRepository) DeleteChat(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockChatRepositoryMockRecorder) DeleteChat(ctx, chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockChatRepository)(nil).DeleteChat), ctx, chatID)
}

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// Transaction mocks base method.
func (m *MockTransactor) Transaction(ctx context.Context, txFunc func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, txFunc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockTransactorMockRecorder) Transaction(ctx, txFunc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockTransactor)(nil).Transaction), ctx, txFunc)
}

// TransactionWithReturn mocks base method.
func (m *MockTransactor) TransactionWithReturn(ctx context.Context, txFunc func(context.Context) (any, error)) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionWithReturn", ctx, txFunc)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionWithReturn indicates an expected call of TransactionWithReturn.
func (mr *MockTransactorMockRecorder) TransactionWithReturn(ctx, txFunc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionWithReturn", reflect.TypeOf((*MockTransactor)(nil).TransactionWithReturn), ctx, txFunc)
}
