// Code generated by MockGen. DO NOT EDIT.
// Source: links_requester.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pkg "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain/pkg"
	scrapper "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain/scrapper"
)

// MockNetworkClient is a mock of NetworkClient interface.
type MockNetworkClient struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkClientMockRecorder
}

// MockNetworkClientMockRecorder is the mock recorder for MockNetworkClient.
type MockNetworkClientMockRecorder struct {
	mock *MockNetworkClient
}

// NewMockNetworkClient creates a new mock instance.
func NewMockNetworkClient(ctrl *gomock.Controller) *MockNetworkClient {
	mock := &MockNetworkClient{ctrl: ctrl}
	mock.recorder = &MockNetworkClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkClient) EXPECT() *MockNetworkClientMockRecorder {
	return m.recorder
}

// DoGithubIssueRequest mocks base method.
func (m *MockNetworkClient) DoGithubIssueRequest(url string) ([]scrapper.GithubIssue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoGithubIssueRequest", url)
	ret0, _ := ret[0].([]scrapper.GithubIssue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoGithubIssueRequest indicates an expected call of DoGithubIssueRequest.
func (mr *MockNetworkClientMockRecorder) DoGithubIssueRequest(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoGithubIssueRequest", reflect.TypeOf((*MockNetworkClient)(nil).DoGithubIssueRequest), url)
}

// DoGithubPullRequestRequest mocks base method.
func (m *MockNetworkClient) DoGithubPullRequestRequest(url string) ([]scrapper.GithubPullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoGithubPullRequestRequest", url)
	ret0, _ := ret[0].([]scrapper.GithubPullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoGithubPullRequestRequest indicates an expected call of DoGithubPullRequestRequest.
func (mr *MockNetworkClientMockRecorder) DoGithubPullRequestRequest(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoGithubPullRequestRequest", reflect.TypeOf((*MockNetworkClient)(nil).DoGithubPullRequestRequest), url)
}

// DoGithubRequest mocks base method.
func (m *MockNetworkClient) DoGithubRequest(url string) (scrapper.GitHubUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoGithubRequest", url)
	ret0, _ := ret[0].(scrapper.GitHubUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoGithubRequest indicates an expected call of DoGithubRequest.
func (mr *MockNetworkClientMockRecorder) DoGithubRequest(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoGithubRequest", reflect.TypeOf((*MockNetworkClient)(nil).DoGithubRequest), url)
}

// DoStackOverflowAnswersRequest mocks base method.
func (m *MockNetworkClient) DoStackOverflowAnswersRequest(url string) (scrapper.StackOverflowAnswersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoStackOverflowAnswersRequest", url)
	ret0, _ := ret[0].(scrapper.StackOverflowAnswersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoStackOverflowAnswersRequest indicates an expected call of DoStackOverflowAnswersRequest.
func (mr *MockNetworkClientMockRecorder) DoStackOverflowAnswersRequest(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoStackOverflowAnswersRequest", reflect.TypeOf((*MockNetworkClient)(nil).DoStackOverflowAnswersRequest), url)
}

// DoStackOverflowCommentsRequest mocks base method.
func (m *MockNetworkClient) DoStackOverflowCommentsRequest(url string) (scrapper.StackOverflowCommentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoStackOverflowCommentsRequest", url)
	ret0, _ := ret[0].(scrapper.StackOverflowCommentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoStackOverflowCommentsRequest indicates an expected call of DoStackOverflowCommentsRequest.
func (mr *MockNetworkClientMockRecorder) DoStackOverflowCommentsRequest(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoStackOverflowCommentsRequest", reflect.TypeOf((*MockNetworkClient)(nil).DoStackOverflowCommentsRequest), url)
}

// DoStackOverflowQuestionRequest mocks base method.
func (m *MockNetworkClient) DoStackOverflowQuestionRequest(url string) (scrapper.StackOverflowUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoStackOverflowQuestionRequest", url)
	ret0, _ := ret[0].(scrapper.StackOverflowUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoStackOverflowQuestionRequest indicates an expected call of DoStackOverflowQuestionRequest.
func (mr *MockNetworkClientMockRecorder) DoStackOverflowQuestionRequest(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoStackOverflowQuestionRequest", reflect.TypeOf((*MockNetworkClient)(nil).DoStackOverflowQuestionRequest), url)
}

// SendLinkUpdate mocks base method.
func (m *MockNetworkClient) SendLinkUpdate(update pkg.LinkUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLinkUpdate", update)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendLinkUpdate indicates an expected call of SendLinkUpdate.
func (mr *MockNetworkClientMockRecorder) SendLinkUpdate(update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLinkUpdate", reflect.TypeOf((*MockNetworkClient)(nil).SendLinkUpdate), update)
}
