// Code generated by MockGen. DO NOT EDIT.
// Source: scheduler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	scrapper "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain/scrapper"
	shared "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain/pkg"
)

// MockNetworkClient is a mock of NetworkClient interface.
type MockNetworkClient struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkClientMockRecorder
}

// MockNetworkClientMockRecorder is the mock recorder for MockNetworkClient.
type MockNetworkClientMockRecorder struct {
	mock *MockNetworkClient
}

// NewMockNetworkClient creates a new mock instance.
func NewMockNetworkClient(ctrl *gomock.Controller) *MockNetworkClient {
	mock := &MockNetworkClient{ctrl: ctrl}
	mock.recorder = &MockNetworkClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkClient) EXPECT() *MockNetworkClientMockRecorder {
	return m.recorder
}

// DoGithubRequest mocks base method.
func (m *MockNetworkClient) DoGithubRequest(url string) (scrapper.GitHubUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoGithubRequest", url)
	ret0, _ := ret[0].(scrapper.GitHubUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoGithubRequest indicates an expected call of DoGithubRequest.
func (mr *MockNetworkClientMockRecorder) DoGithubRequest(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoGithubRequest", reflect.TypeOf((*MockNetworkClient)(nil).DoGithubRequest), url)
}

// DoStackOverflowRequest mocks base method.
func (m *MockNetworkClient) DoStackOverflowRequest(url string) (scrapper.StackOverflowUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoStackOverflowRequest", url)
	ret0, _ := ret[0].(scrapper.StackOverflowUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoStackOverflowRequest indicates an expected call of DoStackOverflowRequest.
func (mr *MockNetworkClientMockRecorder) DoStackOverflowRequest(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoStackOverflowRequest", reflect.TypeOf((*MockNetworkClient)(nil).DoStackOverflowRequest), url)
}

// SendLinkUpdate mocks base method.
func (m *MockNetworkClient) SendLinkUpdate(update shared.LinkUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLinkUpdate", update)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendLinkUpdate indicates an expected call of SendLinkUpdate.
func (mr *MockNetworkClientMockRecorder) SendLinkUpdate(update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLinkUpdate", reflect.TypeOf((*MockNetworkClient)(nil).SendLinkUpdate), update)
}
