// Code generated by MockGen. DO NOT EDIT.
// Source: updates_grouper.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	agent "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain/agent"
)

// MockUpdatesHandler is a mock of UpdatesHandler interface.
type MockUpdatesHandler struct {
	ctrl     *gomock.Controller
	recorder *MockUpdatesHandlerMockRecorder
}

// MockUpdatesHandlerMockRecorder is the mock recorder for MockUpdatesHandler.
type MockUpdatesHandlerMockRecorder struct {
	mock *MockUpdatesHandler
}

// NewMockUpdatesHandler creates a new mock instance.
func NewMockUpdatesHandler(ctrl *gomock.Controller) *MockUpdatesHandler {
	mock := &MockUpdatesHandler{ctrl: ctrl}
	mock.recorder = &MockUpdatesHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdatesHandler) EXPECT() *MockUpdatesHandlerMockRecorder {
	return m.recorder
}

// FormAndSendUpdate mocks base method.
func (m *MockUpdatesHandler) FormAndSendUpdate(update agent.UpdateToSend) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormAndSendUpdate", update)
	ret0, _ := ret[0].(error)
	return ret0
}

// FormAndSendUpdate indicates an expected call of FormAndSendUpdate.
func (mr *MockUpdatesHandlerMockRecorder) FormAndSendUpdate(update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormAndSendUpdate", reflect.TypeOf((*MockUpdatesHandler)(nil).FormAndSendUpdate), update)
}
