// Code generated by MockGen. DO NOT EDIT.
// Source: fallback_sender.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pkg "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain/pkg"
)

// MockUpdateSender is a mock of UpdateSender interface.
type MockUpdateSender struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateSenderMockRecorder
}

// MockUpdateSenderMockRecorder is the mock recorder for MockUpdateSender.
type MockUpdateSenderMockRecorder struct {
	mock *MockUpdateSender
}

// NewMockUpdateSender creates a new mock instance.
func NewMockUpdateSender(ctrl *gomock.Controller) *MockUpdateSender {
	mock := &MockUpdateSender{ctrl: ctrl}
	mock.recorder = &MockUpdateSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateSender) EXPECT() *MockUpdateSenderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockUpdateSender) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockUpdateSenderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockUpdateSender)(nil).Close))
}

// SendLinkUpdate mocks base method.
func (m *MockUpdateSender) SendLinkUpdate(update pkg.LinkUpdate, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLinkUpdate", update, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendLinkUpdate indicates an expected call of SendLinkUpdate.
func (mr *MockUpdateSenderMockRecorder) SendLinkUpdate(update, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLinkUpdate", reflect.TypeOf((*MockUpdateSender)(nil).SendLinkUpdate), update, key)
}
