// Code generated by MockGen. DO NOT EDIT.
// Source: agent_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	agent "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain/agent"
	pkg "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/domain/pkg"
)

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSender) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockSenderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSender)(nil).Close))
}

// SendLinkUpdate mocks base method.
func (m *MockSender) SendLinkUpdate(update pkg.ProcessedLinkUpdate, eventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLinkUpdate", update, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendLinkUpdate indicates an expected call of SendLinkUpdate.
func (mr *MockSenderMockRecorder) SendLinkUpdate(update, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLinkUpdate", reflect.TypeOf((*MockSender)(nil).SendLinkUpdate), update, eventID)
}

// MockPrioritizer is a mock of Prioritizer interface.
type MockPrioritizer struct {
	ctrl     *gomock.Controller
	recorder *MockPrioritizerMockRecorder
}

// MockPrioritizerMockRecorder is the mock recorder for MockPrioritizer.
type MockPrioritizerMockRecorder struct {
	mock *MockPrioritizer
}

// NewMockPrioritizer creates a new mock instance.
func NewMockPrioritizer(ctrl *gomock.Controller) *MockPrioritizer {
	mock := &MockPrioritizer{ctrl: ctrl}
	mock.recorder = &MockPrioritizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrioritizer) EXPECT() *MockPrioritizerMockRecorder {
	return m.recorder
}

// FindPriority mocks base method.
func (m *MockPrioritizer) FindPriority(description string) agent.Priority {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPriority", description)
	ret0, _ := ret[0].(agent.Priority)
	return ret0
}

// FindPriority indicates an expected call of FindPriority.
func (mr *MockPrioritizerMockRecorder) FindPriority(description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPriority", reflect.TypeOf((*MockPrioritizer)(nil).FindPriority), description)
}

// MockUpdatesSummarizer is a mock of UpdatesSummarizer interface.
type MockUpdatesSummarizer struct {
	ctrl     *gomock.Controller
	recorder *MockUpdatesSummarizerMockRecorder
}

// MockUpdatesSummarizerMockRecorder is the mock recorder for MockUpdatesSummarizer.
type MockUpdatesSummarizerMockRecorder struct {
	mock *MockUpdatesSummarizer
}

// NewMockUpdatesSummarizer creates a new mock instance.
func NewMockUpdatesSummarizer(ctrl *gomock.Controller) *MockUpdatesSummarizer {
	mock := &MockUpdatesSummarizer{ctrl: ctrl}
	mock.recorder = &MockUpdatesSummarizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdatesSummarizer) EXPECT() *MockUpdatesSummarizerMockRecorder {
	return m.recorder
}

// Summarize mocks base method.
func (m *MockUpdatesSummarizer) Summarize(update pkg.LinkUpdate) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", update)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summarize indicates an expected call of Summarize.
func (mr *MockUpdatesSummarizerMockRecorder) Summarize(update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockUpdatesSummarizer)(nil).Summarize), update)
}

// MockUpdatesGrouper is a mock of UpdatesGrouper interface.
type MockUpdatesGrouper struct {
	ctrl     *gomock.Controller
	recorder *MockUpdatesGrouperMockRecorder
}

// MockUpdatesGrouperMockRecorder is the mock recorder for MockUpdatesGrouper.
type MockUpdatesGrouperMockRecorder struct {
	mock *MockUpdatesGrouper
}

// NewMockUpdatesGrouper creates a new mock instance.
func NewMockUpdatesGrouper(ctrl *gomock.Controller) *MockUpdatesGrouper {
	mock := &MockUpdatesGrouper{ctrl: ctrl}
	mock.recorder = &MockUpdatesGrouperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdatesGrouper) EXPECT() *MockUpdatesGrouperMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockUpdatesGrouper) Add(update agent.UpdateToGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", update)
}

// Add indicates an expected call of Add.
func (mr *MockUpdatesGrouperMockRecorder) Add(update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockUpdatesGrouper)(nil).Add), update)
}

// Flush mocks base method.
func (m *MockUpdatesGrouper) Flush() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Flush")
}

// Flush indicates an expected call of Flush.
func (mr *MockUpdatesGrouperMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockUpdatesGrouper)(nil).Flush))
}
